name = "my-app"
compatibility_date = "2025-05-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[rules]]
type = "Data"
globs = ["./data/**/*"]
fallthrough = true

[[rules]]
type = "Text"
type = "CompiledAsset"
globs = ["config.json"]
fallthrough = true
